### ISSUE TITLE
Adding simple bash examples

### ISSUE THREAD

**Issue by jmiskovic** [wejn/yamaha-yas-207#1]
Hi!

I have a similar soundbar, model YAS-107. I'm quite satisfied with features but switching between different sources and volume control is frustrating. Your reverse-engineering notes were a great help, thanks for sharing.

I arrived at this:

```
sudo -s 
bt-device -l | grep YAS                # find out the device address
rfcomm bind rfcomm0 C8:84:xx:xx:xx:xx  # bind bluetooth device to /dev/rfcomm0 serial

echo -en "\xCC\xAA\x03\x40\x78\x4A\xFB" > /dev/rfcomm0   # change the input to HDMI
echo -en "\xCC\xAA\x03\x40\x78\xD1\x74" > /dev/rfcomm0   # change the input to ANALOG
echo -en "\xCC\xAA\x03\x40\x78\x29\x1C" > /dev/rfcomm0   # change the input to BLUETOOTH
echo -en "\xCC\xAA\x03\x40\x78\xDF\x66" > /dev/rfcomm0   # change the input to TV
echo -en "\xCC\xAA\x03\x40\x78\x1E\x27" > /dev/rfcomm0   # volume +
echo -en "\xCC\xAA\x03\x40\x78\x1F\x26" > /dev/rfcomm0   # volume -
echo -en "\xCC\xAA\x03\x40\x78\x7F\xC6" > /dev/rfcomm0   # power off
```

Maybe you could include a section in the readme to provide this basic info for controlling the soundbar from bash? Your project is easy to find by anyone looking to automate the YAS-xxx operation, but not so easy to get up and running.

**Comment by wejn** [comment]
Done, thanks!
