### ISSUE TITLE
Any chance you can make it work with micro-HDMI port?

### ISSUE THREAD

**Issue by eladshabo** [wejn/yamaha-yas-207#2]
first - I really appreciate the work you did from A-to-Z on the YAS-207!! **REALLY!**

I have the same setup at home, RPi4 (running Homebridge of course.. for different HomeKit integrations) with YAS-207 and I would like to be able to control it as well from the Homekit app.
Is there any chance you can modify the code to stream audio from the 2nd microHDMI port instead of the TOSLINK adapter?

**Comment by wejn** [comment]
Hi, I think this solution is independent on what you use for audio. As long as you configure your raspi to stream audio to the hdmi port, it should work just fine...
